### ISSUE TITLE
templates seem to use single quote which confuses chef

### ISSUE THREAD

**Issue by INRIX-Mark-Gershaft** [cabeca/SublimeChef#14]
When I type "template" and use auto-complete it creates:
template 'name' do
	source 'source.erb'
	owner 'root'
	group 'root'
	mode '0644'
end

This is problematic if template is inside a loop and 'name' refuses to take in macro-substitution.

**Comment by cabeca** [comment]
I'm not sure I understand your question. Could you please elaborate?

**Comment by INRIX-Mark-Gershaft** [comment]
I was trying to do following
[...].each do |x|
   template '.../#{x}/...' do
...
   end
end

It appears that chef has special meaning for single quotes and doesn't perform parameter substitution, it does substitute parameters in double quotes.

**Comment by cabeca** [comment]
That's a feature from ruby. If you want string interpolation (evaluation of code inside #{} inside strings) you need to use double quotes. If you use single quotes, the content of the string will be taken literally.

Just change single quotes to double quotes anytime you need to interpolate the strings.
